# Losing non-distinctive features 

I will be using a dataset provided with “The Elements of Statistical Learning: 
Data Mining, Inference, and Prediction” by Trevor Hastie, Robert Tibshirani & Jerome Friedman. 

> Normalized handwritten digits, automatically scanned from envelopes by the U.S. Postal Service. The original scanned digits are binary and of different sizes and orientations; the images here have been deslanted and size normalized, resulting in 16 x 16 grayscale images (Le Cun et al., 1990).
> 
> The data are in two gzipped files, and each line consists of the digit id (0-9) followed by the 256 grayscale values.
> 
> There are 7291 training observations and 2007 test observations [...]

Sources: 
- https://web.stanford.edu/~hastie/ElemStatLearn/datasets/zip.info.txt
- https://web.stanford.edu/~hastie/ElemStatLearn/datasets/zip.test.gz
- https://web.stanford.edu/~hastie/ElemStatLearn/datasets/zip.train.gz
--- 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans

## Importing and preparing the data

In [2]:
# Read CSV file into a pandas DataFrame 
# Does *not* use first line as a header, recognizes white space character as a field separator 
# see https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html 
data = pd.read_csv("data/zip.train", header=None, sep=" ")

In [3]:
data.head()

0    1    2    3      4      5      6      7      8      9   ...     248  \
0  6.0 -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -0.631  0.862 ...   0.823   
1  5.0 -1.0 -1.0 -1.0 -0.813 -0.671 -0.809 -0.887 -0.671 -0.853 ...  -0.671   
2  4.0 -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 ...  -1.000   
3  7.0 -1.0 -1.0 -1.0 -1.000 -1.000 -0.273  0.684  0.960  0.450 ...   1.000   
4  3.0 -1.0 -1.0 -1.0 -1.000 -1.000 -0.928 -0.204  0.751  0.466 ...   0.639   

     249    250    251    252    253    254    255  256  257  
0  1.000  0.482 -0.474 -0.991 -1.000 -1.000 -1.000 -1.0  NaN  
1 -0.033  0.761  0.762  0.126 -0.095 -0.671 -0.828 -1.0  NaN  
2 -1.000 -0.109  1.000 -0.179 -1.000 -1.000 -1.000 -1.0  NaN  
3  0.536 -0.987 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0  NaN  
4  1.000  1.000  0.791  0.439 -0.199 -0.883 -1.000 -1.0  NaN  

[5 rows x 258 columns]

- As described in ```zip.info.txt``` row 0 holds the value of the integer represented by the following 256 grayscale values. 
- Row 257 is NaN because all lines end with a non-printing character. 

In [4]:
# Lose the last column 
del data[257]

- In order to reduce complexity in the data I will downscale the 256 grayscale values to 16. 
- The approximation is: f(x) = int((x+1)*7.5+1)

In [5]:
# selects the first column holding the digit id (0-9)
data_digits = data.iloc[:,0]

In [6]:
data_digits.head()

0    6.0
1    5.0
2    4.0
3    7.0
4    3.0
Name: 0, dtype: float64

In [7]:
"""
The int() method can *not* be applied to a pandas Series, so in ordert to 
convert the values in row 0 to integers I define and apply a lambda function.
"""

int_x = lambda x: int(x)
data_digits = data_digits.apply(int_x)

In [8]:
data_digits.head()

0    6
1    5
2    4
3    7
4    3
Name: 0, dtype: int64

In [9]:
# extract the columns holding the grayscale values and apply rescaling function 

data_grayscale_values = (data.iloc[:,1:257]).apply(lambda x: (x+1)*7.5+1)

In [10]:
data_grayscale_values.head()

1    2    3       4       5       6        7        8        9        10   \
0  1.0  1.0  1.0  1.0000  1.0000  1.0000   1.0000   3.7675  14.9650   7.2475   
1  1.0  1.0  1.0  2.4025  3.4675  2.4325   1.8475   3.4675   2.1025   1.0000   
2  1.0  1.0  1.0  1.0000  1.0000  1.0000   1.0000   1.0000   1.0000   1.0300   
3  1.0  1.0  1.0  1.0000  1.0000  6.4525  13.6300  15.7000  11.8750   7.9975   
4  1.0  1.0  1.0  1.0000  1.0000  1.5400   6.9700  14.1325  11.9950  10.2550   

  ...       247      248      249      250      251      252     253     254  \
0 ...   10.7800  14.6725  16.0000  12.1150   4.9450   1.0675  1.0000  1.0000   
1 ...    3.4675   3.4675   8.2525  14.2075  14.2150   9.4450  7.7875  3.4675   
2 ...    1.0000   1.0000   1.0000   7.6825  16.0000   7.1575  1.0000  1.0000   
3 ...    6.1150  16.0000  12.5200   1.0975   1.0000   1.0000  1.0000  1.0000   
4 ...   11.9950  13.2925  16.0000  16.0000  14.4325  11.7925  7.0075  1.8775   

    255  256  
0  1.00  1.0  
1  2.29  1.0  
2  1.00  1.0  
3  1.00  1.0  
4  1.00  1.0  

[5 rows x 256 columns]

In [11]:
# rounds floats to nearest integer-like floats 

data_grayscale_values = np.round(data_grayscale_values)

In [12]:
data_rc = pd.concat([data_digits, np.round(data_grayscale_values)], axis=1)

In [13]:
data_rc.head()

0    1    2    3    4    5    6     7     8     9   ...    247   248   249  \
0    6  1.0  1.0  1.0  1.0  1.0  1.0   1.0   4.0  15.0 ...   11.0  15.0  16.0   
1    5  1.0  1.0  1.0  2.0  3.0  2.0   2.0   3.0   2.0 ...    3.0   3.0   8.0   
2    4  1.0  1.0  1.0  1.0  1.0  1.0   1.0   1.0   1.0 ...    1.0   1.0   1.0   
3    7  1.0  1.0  1.0  1.0  1.0  6.0  14.0  16.0  12.0 ...    6.0  16.0  13.0   
4    3  1.0  1.0  1.0  1.0  1.0  2.0   7.0  14.0  12.0 ...   12.0  13.0  16.0   

    250   251   252  253  254  255  256  
0  12.0   5.0   1.0  1.0  1.0  1.0  1.0  
1  14.0  14.0   9.0  8.0  3.0  2.0  1.0  
2   8.0  16.0   7.0  1.0  1.0  1.0  1.0  
3   1.0   1.0   1.0  1.0  1.0  1.0  1.0  
4  16.0  14.0  12.0  7.0  2.0  1.0  1.0  

[5 rows x 257 columns]

## Losing non-distintinctive features 

Identify pixels have (approximately) the same value for all digits in our sample, i.e. columns with small to null variance (standard deviation ~ 0). 

In [45]:
data_grayscale_values_description = data_grayscale_values.describe()

In [48]:
data_grayscale_values_description.head()

1            2            3            4            5    \
count  7291.000000  7291.000000  7291.000000  7291.000000  7291.000000   
mean      1.026882     1.140859     1.366068     1.839254     2.691538   
std       0.388577     1.132046     1.836005     2.703897     3.768639   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%       1.000000     1.000000     1.000000     1.000000     1.000000   

               6            7            8            9            10   \
count  7291.000000  7291.000000  7291.000000  7291.000000  7291.000000   
mean      3.917707     5.726375     8.158414     8.101084     6.358799   
std       4.724025     5.384593     5.775000     5.656933     5.611024   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%       1.000000     1.000000     1.000000     1.000000     1.000000   

          ...               247          248          249          250  \
count     ...       7291.000000  7291.000000  7291.000000  7291.000000   
mean      ...          7.003292     9.546290     9.375394     6.141407   
std       ...          5.809622     5.658759     5.690166     5.458903   
min       ...          1.000000     1.000000     1.000000     1.000000   
25%       ...          1.000000     4.000000     3.000000     1.000000   

               251          252          253          254          255  \
count  7291.000000  7291.000000  7291.000000  7291.000000  7291.000000   
mean      3.593060     2.212317     1.580167     1.319435     1.154163   
std       4.375916     3.112022     2.260045     1.722483     1.184880   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%       1.000000     1.000000     1.000000     1.000000     1.000000   

               256  
count  7291.000000  
mean      1.039775  
std       0.501365  
min       1.000000  
25%       1.000000  

[5 rows x 256 columns]

In [50]:
# print values for standard deviation (std) 
data_grayscale_values_description.iloc[2,:]

1      0.388577
2      1.132046
3      1.836005
4      2.703897
5      3.768639
6      4.724025
7      5.384593
8      5.775000
9      5.656933
10     5.611024
11     5.154749
12     4.398392
13     3.566084
14     2.549625
15     1.473684
16     0.565154
17     0.769299
18     1.927320
19     3.213899
20     4.641557
21     5.863785
22     6.456181
23     6.283067
24     5.667892
25     5.553273
26     6.209355
27     6.476293
28     6.091374
29     5.195350
30     3.957087
         ...   
227    3.747480
228    5.219354
229    6.299515
230    6.716570
231    6.246226
232    5.426194
233    5.391054
234    6.420093
235    6.556522
236    5.741086
237    4.421212
238    3.158902
239    2.194735
240    1.112709
241    0.351053
242    1.055412
243    1.780577
244    2.806008
245    3.946482
246    5.099506
247    5.809622
248    5.658759
249    5.690166
250    5.458903
251    4.375916
252    3.112022
253    2.260045
254    1.722483
255    1.184880
256    0.501365
Name: std, Length: 256, 

In [71]:
[data_grayscale_values_description.iloc[2,:] < 1]

[1       True
 2      False
 3      False
 4      False
 5      False
 6      False
 7      False
 8      False
 9      False
 10     False
 11     False
 12     False
 13     False
 14     False
 15     False
 16      True
 17      True
 18     False
 19     False
 20     False
 21     False
 22     False
 23     False
 24     False
 25     False
 26     False
 27     False
 28     False
 29     False
 30     False
        ...  
 227    False
 228    False
 229    False
 230    False
 231    False
 232    False
 233    False
 234    False
 235    False
 236    False
 237    False
 238    False
 239    False
 240    False
 241     True
 242    False
 243    False
 244    False
 245    False
 246    False
 247    False
 248    False
 249    False
 250    False
 251    False
 252    False
 253    False
 254    False
 255    False
 256     True
 Name: std, Length: 256, dtype: bool]